import "../imports/api/users.js";
import "../imports/api/questions.js";
import "../imports/api/notifications.js";
import "../imports/api/rooms.js";
import "../imports/api/badges.js";
import "../imports/api/userBadges.js";
import "../imports/api/feedbackTypes.js";
import "../imports/api/activateBadges.js";
import "../imports/api/activateQuestions.js";