import "./home.html";
import "../login/login.js";
import "../activeQuestion/activeQuestion.js";
import "../selectRoom/selectRoom.js";
import "../questions/questions.js";
import "../rooms/rooms.js";
import "../badges/badges.js";
import "../feedbackTypes/feedbackTypes.js";
import "../images/images.js";